Profiling riders dataset

In [171]:
import pandas as pd
import numpy as np

# Dictionary containing dataset names and date columns
data_files = {
    "sessions": ["session_time"],
    "trips": ["pickup_time", "dropoff_time"],
    "riders": ["signup_date"],
    "drivers": ["signup_date", "last_active"],
    "promotions": ["start_date", "end_date"]
}

# Dictionary to store DataFrames
dfs = {}

# Load all datasets
for name, date_cols in data_files.items():
    dfs[name] = pd.read_csv(
        f"../data/raw/{name}.csv",
        parse_dates=date_cols
    )

# Assign DataFrames to variables
sessions = dfs["sessions"]
trips = dfs["trips"]
riders = dfs["riders"]
drivers = dfs["drivers"]
promotions = dfs["promotions"]

In [123]:
# Display the first five rows to understand the structure of the dataset

dfs['riders'].head()

,user_id,signup_date,loyalty_status,age,city,avg_rating_given,churn_prob,referred_by
0,R00000,2025-01-24,Bronze,34.729629,Nairobi,5.0,0.142431,R00001
1,R00001,2024-09-09,Bronze,34.571020,Nairobi,4.7,0.674161,NaN
2,R00002,2024-09-07,Bronze,47.133960,Lagos,4.2,0.510379,NaN
3,R00003,2025-03-17,Bronze,41.658628,Nairobi,4.9,0.244779,NaN
4,R00004,2024-08-20,Silver,40.681709,Lagos,3.9,0.269960,R00002

In [124]:
# Display the number of rows and columns
dfs["riders"].shape

(10000, 8)

In [125]:
dfs["riders"].info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id           10000 non-null  str
 1   signup_date       10000 non-null  datetime64[us]
 2   loyalty_status    10000 non-null  str
 3   age               10000 non-null  float64
 4   city              10000 non-null  str
 5   avg_rating_given  10000 non-null  float64
 6   churn_prob        10000 non-null  float64
 7   referred_by       3053 non-null   str
dtypes: datetime64[us](1), float64(3), str(4)
memory usage: 815.6 KB

In [126]:
dfs["riders"].dtypes

user_id                        str
signup_date         datetime64[us]
loyalty_status                 str
age                        float64
city                           str
avg_rating_given           float64
churn_prob                 float64
referred_by                    str
dtype: object

In [127]:
dfs["riders"].describe()

               signup_date           age  avg_rating_given    churn_prob
count                10000  10000.000000      10000.000000  10000.000000
mean   2024-04-27 00:28:48     35.154221          4.461510      0.286168
min    2023-04-27 00:00:00     18.000000          2.600000      0.002934
25%    2023-10-27 00:00:00     28.317568          4.200000      0.161691
50%    2024-04-25 00:00:00     35.037671          4.500000      0.266712
75%    2024-10-31 00:00:00     41.691186          4.800000      0.388812
max    2025-04-26 00:00:00     70.000000          5.000000      0.913302
std                    NaN      9.545528          0.429162      0.159029

In [128]:
dfs["riders"].describe(include="object")

C:\Users\User.DESKTOP-775\AppData\Local\Temp\ipykernel_31880\3054084399.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  dfs["riders"].describe(include="object")

       user_id loyalty_status   city referred_by
count    10000          10000  10000        3053
unique   10000              4      3        1660
top     R00000         Bronze  Cairo      R00002
freq         1           6057   3374          46

In [129]:
dfs["riders"].isnull().sum()

user_id                0
signup_date            0
loyalty_status         0
age                    0
city                   0
avg_rating_given       0
churn_prob             0
referred_by         6947
dtype: int64

In [130]:
# Check whether the dataset contains fully duplicated rows
print("Duplicate rows:", riders.duplicated().sum())

Duplicate rows: 0

In [131]:

# user_id should be unique because each row should represent one rider
print("Duplicate user IDs:", riders["user_id"].duplicated().sum())

Duplicate user IDs: 0

In [132]:
for col in dfs["riders"].select_dtypes(include=["object", "bool"]).columns:
    print(f"\nColumn: {col}")
    print("-" * 40)
    print(dfs["riders"][col].value_counts(dropna=False))

Column: user_id
----------------------------------------
user_id
R00000    1
R00001    1
R00002    1
R00003    1
R00004    1
         ..
R09995    1
R09996    1
R09997    1
R09998    1
R09999    1
Name: count, Length: 10000, dtype: int64

Column: loyalty_status
----------------------------------------
loyalty_status
Bronze      6057
Silver      2425
Gold        1050
Platinum     468
Name: count, dtype: int64

Column: city
----------------------------------------
city
Cairo      3374
Nairobi    3330
Lagos      3296
Name: count, dtype: int64

Column: referred_by
----------------------------------------
referred_by
NaN       6947
R00002      46
R00001      33
R00033      32
R00030      24
          ...
R08187       1
R08370       1
R09768       1
R02155       1
R07447       1
Name: count, Length: 1661, dtype: int64

C:\Users\User.DESKTOP-775\AppData\Local\Temp\ipykernel_31880\1203076070.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in dfs["riders"].select_dtypes(include=["object", "bool"]).columns:

In [133]:
dfs["riders"].nunique()

user_id             10000
signup_date           731
loyalty_status          4
age                  9553
city                    3
avg_rating_given       23
churn_prob          10000
referred_by          1660
dtype: int64

In [134]:
# Calculate missing values and missing percentage for each column
missing_values = pd.DataFrame({
    "Missing Values": riders.isnull().sum(),
    "Percentage (%)": (riders.isnull().mean() * 100).round(2)
})

missing_values

                  Missing Values  Percentage (%)
user_id                        0            0.00
signup_date                    0            0.00
loyalty_status                 0            0.00
age                            0            0.00
city                           0            0.00
avg_rating_given               0            0.00
churn_prob                     0            0.00
referred_by                 6947           69.47

In [135]:
dfs["riders"]["city"].value_counts()

city
Cairo      3374
Nairobi    3330
Lagos      3296
Name: count, dtype: int64

In [136]:
# Count unique values in each column to understand cardinality
unique_values = pd.DataFrame({
    "Unique Values": riders.nunique()
}).sort_values(by="Unique Values")

unique_values

                  Unique Values
city                          3
loyalty_status                4
avg_rating_given             23
signup_date                 731
referred_by                1660
age                        9553
user_id                   10000
churn_prob                10000

In [137]:
dfs['riders'].head()

,user_id,signup_date,loyalty_status,age,city,avg_rating_given,churn_prob,referred_by
0,R00000,2025-01-24,Bronze,34.729629,Nairobi,5.0,0.142431,R00001
1,R00001,2024-09-09,Bronze,34.571020,Nairobi,4.7,0.674161,NaN
2,R00002,2024-09-07,Bronze,47.133960,Lagos,4.2,0.510379,NaN
3,R00003,2025-03-17,Bronze,41.658628,Nairobi,4.9,0.244779,NaN
4,R00004,2024-08-20,Silver,40.681709,Lagos,3.9,0.269960,R00002

 Profiling Trips Dataset

In [138]:
# Display the first five rows of the trips dataset
dfs["trips"].head()

,trip_id,user_id,driver_id,fare,surge_multiplier,tip,payment_type,pickup_time,dropoff_time,pickup_lat,pickup_lng,dropoff_lat,dropoff_lng,weather,city,loyalty_status
0,T000000,R05207,D00315,12.11,1.0,0.00,Card,2024-11-27 18:41:50+02:27,2024-11-27 19:33:50+02:27,-1.108123,36.912209,-1.068155,36.875377,Foggy,Nairobi,Bronze
1,T000001,R09453,D03717,8.73,1.0,0.02,Card,2024-10-28 23:13:48+00:14,2024-10-28 23:26:48+00:14,6.675266,3.515740,6.641734,3.525620,Sunny,Lagos,Gold
2,T000002,R00567,D02035,19.68,1.0,0.00,Card,2025-02-17 05:36:41+02:27,2025-02-17 05:52:41+02:27,-1.248589,37.010668,-1.273182,37.018586,Cloudy,Nairobi,Bronze
3,T000003,R09573,D02657,16.43,1.0,0.01,Mobile Money,2024-06-18 19:27:14+02:05,2024-06-18 19:32:14+02:05,29.819554,31.188780,29.837689,31.232978,Cloudy,Cairo,Bronze
4,T000004,R03446,D01026,8.70,1.0,1.06,Card,2024-10-05 09:58:16+02:27,2024-10-05 10:28:16+02:27,-1.676479,36.729219,-1.638395,36.694063,Sunny,Nairobi,Gold

In [139]:
# Display the number of rows and columns in the dataset
dfs["trips"].shape

(200000, 16)

In [140]:
# Display dataset information
dfs["trips"].info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   trip_id           200000 non-null  str
 1   user_id           200000 non-null  str
 2   driver_id         200000 non-null  str
 3   fare              200000 non-null  float64
 4   surge_multiplier  200000 non-null  float64
 5   tip               200000 non-null  float64
 6   payment_type      200000 non-null  str
 7   pickup_time       200000 non-null  str
 8   dropoff_time      200000 non-null  str
 9   pickup_lat        200000 non-null  float64
 10  pickup_lng        200000 non-null  float64
 11  dropoff_lat       200000 non-null  float64
 12  dropoff_lng       200000 non-null  float64
 13  weather           200000 non-null  str
 14  city              200000 non-null  str
 15  loyalty_status    200000 non-null  str
dtypes: float64(7), str(9)
memory usage: 42.1 MB

In [141]:
# Display summary statistics for numerical columns
dfs["trips"].describe()

,fare,surge_multiplier,tip,pickup_lat,pickup_lng,dropoff_lat,dropoff_lng
count,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000
mean,15.401285,1.141500,0.469566,11.849600,23.924133,11.849589,23.924173
std,6.163199,0.255362,1.100545,13.362151,14.577572,13.362229,14.577642
min,2.970000,1.000000,0.000000,-1.786360,2.879224,-1.833220,2.830979
25%,11.000000,1.000000,0.000000,-1.172683,3.496574,-1.172868,3.497195
50%,14.130000,1.000000,0.000000,6.525574,31.238814,6.525235,31.239118
75%,18.350000,1.200000,0.400000,29.934766,36.703772,29.935056,36.704067
max,82.740000,3.800000,21.860000,30.544251,37.317090,30.592457,37.364817

In [142]:
# Display summary statistics for both object and string columns
dfs["trips"].describe(include=["object", "string"])

,trip_id,user_id,driver_id,payment_type,pickup_time,dropoff_time,weather,city,loyalty_status
count,200000,200000,200000,200000,200000,200000,200000,200000,200000
unique,200000,10000,5000,3,199690,199663,4,3,4
top,T000000,R08152,D03093,Card,2025-01-11 13:56:07+02:27,2024-07-21 09:14:10+02:27,Sunny,Cairo,Bronze
freq,1,42,67,100326,2,3,120151,67436,121252

In [143]:
# Display the number of missing values in each column
dfs["trips"].isnull().sum()

trip_id             0
user_id             0
driver_id           0
fare                0
surge_multiplier    0
tip                 0
payment_type        0
pickup_time         0
dropoff_time        0
pickup_lat          0
pickup_lng          0
dropoff_lat         0
dropoff_lng         0
weather             0
city                0
loyalty_status      0
dtype: int64

In [144]:
# Count the number of duplicate rows in the dataset
dfs["trips"].duplicated().sum()

np.int64(0)

In [145]:
# Display the number of unique values in each column
dfs["trips"].nunique()

trip_id             200000
user_id              10000
driver_id             5000
fare                  4224
surge_multiplier        27
tip                   1088
payment_type             3
pickup_time         199690
dropoff_time        199663
pickup_lat          200000
pickup_lng          200000
dropoff_lat         200000
dropoff_lng         200000
weather                  4
city                     3
loyalty_status           4
dtype: int64

In [146]:
# Display the frequency of each category
# for selected categorical columns

categorical_columns = [
    "payment_type",
    "weather",
    "city",
    "loyalty_status"
]

for col in categorical_columns:

    print(f"\nColumn: {col}")
    print("-" * 40)

    # Display the frequency of each category
    # including missing values
    print(dfs["trips"][col].value_counts(dropna=False))

Column: payment_type
----------------------------------------
payment_type
Card            100326
Mobile Money     79661
Cash             20013
Name: count, dtype: int64

Column: weather
----------------------------------------
weather
Sunny     120151
Rainy      39976
Cloudy     29874
Foggy       9999
Name: count, dtype: int64

Column: city
----------------------------------------
city
Cairo      67436
Nairobi    66705
Lagos      65859
Name: count, dtype: int64

Column: loyalty_status
----------------------------------------
loyalty_status
Bronze      121252
Silver       48332
Gold         21044
Platinum      9372
Name: count, dtype: int64

In [147]:
# Display the earliest and latest pickup times
print("Pickup Time")
print(dfs["trips"]["pickup_time"].min())
print(dfs["trips"]["pickup_time"].max())

print()

# Display the earliest and latest dropoff times
print("Dropoff Time")
print(dfs["trips"]["dropoff_time"].min())
print(dfs["trips"]["dropoff_time"].max())

Pickup Time
2024-04-27 00:07:34+02:27
2025-04-27 23:57:26+00:14

Dropoff Time
2024-04-27 00:24:28+02:05
2025-04-28 00:26:26+00:14

Profiling drivers Dataset

In [148]:
# Create a copy of the original drivers dataset
# This prevents changes from affecting the raw data
drivers_clean = drivers.copy()

# Display the number of rows and columns
print("Original shape:", drivers_clean.shape)

# Display the data types of each column
print("\nData Types:")
print(drivers_clean.dtypes)

# Check for duplicate rows
print("\nDuplicate rows:", drivers_clean.duplicated().sum())

# Check for duplicate Driver IDs
print("Duplicate Driver IDs:",
      drivers_clean["driver_id"].duplicated().sum())

# Check for missing values in each column
print("\nMissing values:")
print(drivers_clean.isnull().sum())

# Preview the first five records
display(drivers_clean.head())

Original shape: (5000, 7)

Data Types:
driver_id                     str
rating                    float64
vehicle_type                  str
signup_date        datetime64[us]
last_active        datetime64[us]
city                          str
acceptance_rate           float64
dtype: object

Duplicate rows: 0
Duplicate Driver IDs: 0

Missing values:
driver_id          0
rating             0
vehicle_type       0
signup_date        0
last_active        0
city               0
acceptance_rate    0
dtype: int64

,driver_id,rating,vehicle_type,signup_date,last_active,city,acceptance_rate
0,D00000,3.1,SUV,2025-01-20,2025-01-06 18:23:09.312275,Cairo,0.679555
1,D00001,5.0,Sedan,2023-03-27,2025-04-27 01:44:02.472554,Nairobi,0.548786
2,D00002,4.5,Motorcycle,2024-05-02,2025-03-07 19:24:46.367672,Nairobi,0.593724
3,D00003,5.0,Motorcycle,2023-04-16,2025-03-26 19:16:24.253793,Nairobi,0.990000
4,D00004,4.4,Motorcycle,2023-05-28,2025-04-08 18:54:44.649615,Lagos,0.519773

In [149]:
# Display descriptive statistics for both numeric
# and categorical columns
display(drivers_clean.describe(include="all"))

,driver_id,rating,vehicle_type,signup_date,last_active,city,acceptance_rate
count,5000,5000.000000,5000,5000,5000,5000,5000.000000
unique,5000,NaN,4,NaN,NaN,3,NaN
top,D00000,NaN,Sedan,NaN,NaN,Lagos,NaN
freq,1,NaN,2439,NaN,NaN,1720,NaN
mean,NaN,4.172440,NaN,2023-10-24 01:58:22.080000,2025-03-07 13:50:29.265986,NaN,0.695318
min,NaN,3.100000,NaN,2022-04-27 00:00:00,2022-04-28 16:45:23.765979,NaN,0.100000
25%,NaN,3.700000,NaN,2023-01-18 18:00:00,2025-03-13 08:03:29.754490,NaN,0.565169
50%,NaN,4.200000,NaN,2023-10-20 00:00:00,2025-04-08 11:24:16.190847,NaN,0.697731
75%,NaN,4.700000,NaN,2024-07-28 00:00:00,2025-04-19 19:19:43.007321,NaN,0.837700
max,NaN,5.000000,NaN,2025-04-26 00:00:00,2025-04-27 16:20:56.061019,NaN,0.990000
std,NaN,0.594073,NaN,NaN,NaN,NaN,0.186216

In [150]:

# Check Date Ranges

# Display the earliest and latest driver signup dates
print("Driver Signup Date Range")
print("-" * 35)
print(f"Earliest Signup Date : {drivers_clean['signup_date'].min()}")
print(f"Latest Signup Date   : {drivers_clean['signup_date'].max()}")

# Display the earliest and latest driver activity dates
print("\nDriver Last Active Date Range")
print("-" * 35)
print(f"First Activity Date  : {drivers_clean['last_active'].min()}")
print(f"Latest Activity Date : {drivers_clean['last_active'].max()}")

Driver Signup Date Range
-----------------------------------
Earliest Signup Date : 2022-04-27 00:00:00
Latest Signup Date   : 2025-04-26 00:00:00

Driver Last Active Date Range
-----------------------------------
First Activity Date  : 2022-04-28 16:45:23.765979
Latest Activity Date : 2025-04-27 16:20:56.061019

In [151]:
# Count the number of drivers in each vehicle category
print(drivers_clean["vehicle_type"].value_counts())

vehicle_type
Sedan         2439
SUV           1742
Motorcycle     675
Luxury         144
Name: count, dtype: int64

In [152]:
# Count the number of drivers in each city
print(drivers_clean["city"].value_counts())

city
Lagos      1720
Nairobi    1709
Cairo      1571
Name: count, dtype: int64

In [153]:
# Display summary statistics for driver ratings
print(drivers_clean["rating"].describe())

count    5000.000000
mean        4.172440
std         0.594073
min         3.100000
25%         3.700000
50%         4.200000
75%         4.700000
max         5.000000
Name: rating, dtype: float64

In [154]:
# Display summary statistics for acceptance rate
print(drivers_clean["acceptance_rate"].describe())

count    5000.000000
mean        0.695318
std         0.186216
min         0.100000
25%         0.565169
50%         0.697731
75%         0.837700
max         0.990000
Name: acceptance_rate, dtype: float64

In [155]:
# Ratings should normally fall between 1 and 5

invalid_rating = drivers_clean[
    (drivers_clean["rating"] < 1) |
    (drivers_clean["rating"] > 5)
]

print("Invalid ratings:", len(invalid_rating))

Invalid ratings: 0

In [156]:
# Acceptance rate should be between 0 and 1

invalid_acceptance = drivers_clean[
    (drivers_clean["acceptance_rate"] < 0) |
    (drivers_clean["acceptance_rate"] > 1)
]

print("Invalid acceptance rates:", len(invalid_acceptance))

Invalid acceptance rates: 0

In [157]:
# Calculate the Interquartile Range (IQR)

Q1 = drivers_clean["rating"].quantile(0.25)
Q3 = drivers_clean["rating"].quantile(0.75)

IQR = Q3 - Q1

# Calculate lower and upper limits

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

# Identify outliers

outliers = drivers_clean[
    (drivers_clean["rating"] < lower) |
    (drivers_clean["rating"] > upper)
]

print("Rating Outliers:", len(outliers))

Rating Outliers: 0

In [158]:
# Display a summary of the dataset after profiling

print("Original shape:", drivers_clean.shape)
print("Cleaned shape:", drivers_clean.shape)

print("\nDuplicate rows:", drivers_clean.duplicated().sum())

print("Duplicate Driver IDs:",
      drivers_clean["driver_id"].duplicated().sum())

print("\nMissing values:")
print(drivers_clean.isnull().sum())

Original shape: (5000, 7)
Cleaned shape: (5000, 7)

Duplicate rows: 0
Duplicate Driver IDs: 0

Missing values:
driver_id          0
rating             0
vehicle_type       0
signup_date        0
last_active        0
city               0
acceptance_rate    0
dtype: int64

     Profiling Session Dataset

In [172]:


# Display the number of rows and columns
print("Original shape:", sessions_clean.shape)

# Display the data types of each column
print("\nData Types:")
print(sessions_clean.dtypes)

# Check for duplicate rows
print("\nDuplicate rows:", sessions_clean.duplicated().sum())

# Check for duplicate Session IDs
print("Duplicate Session IDs:",
      sessions_clean["session_id"].duplicated().sum())

# Check for missing values
print("\nMissing values:")
print(sessions_clean.isnull().sum())

# Preview the dataset
display(sessions_clean.head())

Original shape: (50000, 8)

Data Types:
session_id          str
rider_id            str
session_time        str
time_on_app       int64
pages_visited     int64
converted         int64
city                str
loyalty_status      str
dtype: object

Duplicate rows: 0
Duplicate Session IDs: 0

Missing values:
session_id        0
rider_id          0
session_time      0
time_on_app       0
pages_visited     0
converted         0
city              0
loyalty_status    0
dtype: int64

,session_id,rider_id,session_time,time_on_app,pages_visited,converted,city,loyalty_status
0,S000000,R08605,2025-04-27 18:57:06+02:05,79,4,1,Cairo,Bronze
1,S000001,R08823,2025-04-27 07:32:22+02:27,101,3,0,Nairobi,Silver
2,S000002,R05342,2025-04-27 23:17:25+02:05,12,1,0,Cairo,Bronze
3,S000003,R05057,2025-04-27 14:40:25+00:14,19,1,0,Lagos,Silver
4,S000004,R09614,2025-04-27 08:31:22+00:14,4,1,0,Lagos,Bronze

In [160]:
# Display descriptive statistics for both
# numerical and categorical columns
display(sessions_clean.describe(include="all"))

,session_id,rider_id,session_time,time_on_app,pages_visited,converted,city,loyalty_status
count,50000,50000,50000,50000.000000,50000.000000,50000.000000,50000,50000
unique,50000,9929,44513,NaN,NaN,NaN,3,4
top,S000000,R03390,2025-04-27 17:14:41+02:05,NaN,NaN,NaN,Cairo,Bronze
freq,1,16,5,NaN,NaN,NaN,16967,30298
mean,NaN,NaN,NaN,97.940880,2.766360,0.156280,NaN,NaN
std,NaN,NaN,NaN,211.675749,1.554137,0.363124,NaN,NaN
min,NaN,NaN,NaN,0.000000,1.000000,0.000000,NaN,NaN
25%,NaN,NaN,NaN,12.000000,1.000000,0.000000,NaN,NaN
50%,NaN,NaN,NaN,35.000000,2.000000,0.000000,NaN,NaN
75%,NaN,NaN,NaN,90.000000,4.000000,0.000000,NaN,NaN
max,NaN,NaN,NaN,1800.000000,5.000000,1.000000,NaN,NaN

In [161]:
# Display the earliest and latest session times

print("Session Time Range:")
print(
    sessions_clean["session_time"].min(),
    "to",
    sessions_clean["session_time"].max()
)

Session Time Range:
2025-04-27 00:00:00+02:05 to 2025-04-27 23:59:59+00:14

In [162]:
# Count sessions by city

print(sessions_clean["city"].value_counts())

city
Cairo      16967
Nairobi    16598
Lagos      16435
Name: count, dtype: int64

In [163]:
# Count sessions by loyalty status

print(sessions_clean["loyalty_status"].value_counts())

loyalty_status
Bronze      30298
Silver      12170
Gold         5197
Platinum     2335
Name: count, dtype: int64

In [164]:
# Display summary statistics for time spent on the app

print(sessions_clean["time_on_app"].describe())

count    50000.000000
mean        97.940880
std        211.675749
min          0.000000
25%         12.000000
50%         35.000000
75%         90.000000
max       1800.000000
Name: time_on_app, dtype: float64

In [165]:

# Numerical Variables

sessions.describe().T

                 count      mean         std  min   25%   50%   75%     max
time_on_app    50000.0  97.94088  211.675749  0.0  12.0  35.0  90.0  1800.0
pages_visited  50000.0   2.76636    1.554137  1.0   1.0   2.0   4.0     5.0
converted      50000.0   0.15628    0.363124  0.0   0.0   0.0   0.0     1.0

In [166]:
# Categorical Variables


exclude_cols = ["session_id", "rider_id"]

for col in sessions.select_dtypes(include=["object", "bool"]).columns:

    if col in exclude_cols:
        continue

    print(f"\nColumn: {col}")
    print("-"*50)

    summary = (
        sessions[col]
        .value_counts(dropna=False)
        .rename("Count")
        .to_frame()
    )

    summary["Percentage (%)"] = (
        summary["Count"] / len(sessions) * 100
    ).round(2)

    print(summary)

Column: session_time
--------------------------------------------------
                           Count  Percentage (%)
session_time
2025-04-27 17:14:41+02:05      5            0.01
2025-04-27 07:57:12+02:05      5            0.01
2025-04-27 07:49:38+00:14      5            0.01
2025-04-27 17:07:54+02:27      4            0.01
2025-04-27 07:02:27+02:27      4            0.01
...                          ...             ...
2025-04-27 18:21:31+02:27      1            0.00
2025-04-27 16:52:12+02:05      1            0.00
2025-04-27 14:02:26+02:27      1            0.00
2025-04-27 03:45:34+00:14      1            0.00
2025-04-27 17:18:42+02:27      1            0.00

[44513 rows x 2 columns]

Column: city
--------------------------------------------------
         Count  Percentage (%)
city
Cairo    16967           33.93
Nairobi  16598           33.20
Lagos    16435           32.87

Column: loyalty_status
--------------------------------------------------
                Count  Percentage (%)
loyalty_status
Bronze          30298           60.60
Silver          12170           24.34
Gold             5197           10.39
Platinum         2335            4.67

C:\Users\User.DESKTOP-775\AppData\Local\Temp\ipykernel_31880\4267147870.py:6: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in sessions.select_dtypes(include=["object", "bool"]).columns:

In [167]:

# Session Date Range

print("Earliest Session:")
print(sessions["session_time"].min())

print()

print("Latest Session:")
print(sessions["session_time"].max())

Earliest Session:
2025-04-27 00:00:00+02:05

Latest Session:
2025-04-27 23:59:59+00:14

In [168]:
# Numerical Validation

print(
    "Time on App Valid:",
    (sessions["time_on_app"] >= 0).all()
)

print(
    "Pages Visited Valid:",
    sessions["pages_visited"].between(1,5).all()
)

print(
    "Converted Valid:",
    sessions["converted"].isin([0,1]).all()
)

Time on App Valid: True
Pages Visited Valid: True
Converted Valid: True

In [169]:
# Check Extreme Values

print("Maximum Time on App:")
print(sessions["time_on_app"].max())

print()

print("Minimum Time on App:")
print(sessions["time_on_app"].min())

Maximum Time on App:
1800

Minimum Time on App:
0

In [170]:

# Conversion Distribution


conversion = pd.DataFrame({
    "Count": sessions["converted"].value_counts(),
    "Percentage (%)":
        (
            sessions["converted"]
            .value_counts(normalize=True)*100
        ).round(2)
})

conversion

           Count  Percentage (%)
converted
0          42186           84.37
1           7814           15.63

     Profiling Promotions Dataset

In [174]:
# Create a copy of the promotions dataset
promotions = dfs["promotions"]

In [175]:
# Display the first five records
promotions.head()

,promo_id,promo_name,promo_type,promo_value,start_date,end_date,target_segment,city_scope,ab_test_groups,test_allocation,success_metric
0,P000,Peak Hour Pass,surge_waiver,1.0,2025-04-26,2025-05-25,All,Nairobi,['All'],[1.0],Usage Frequency
1,P001,Peak Hour Pass,surge_waiver,1.0,2025-04-26,2025-05-22,All,Cairo,"['Control', 'Variant A', 'Variant B']","[0.3, 0.4, 0.3]",Conversion Rate
2,P002,Peak Hour Pass,surge_waiver,1.0,2025-04-26,2025-05-16,All,Cairo,"['Control', 'Variant A', 'Variant B']","[0.3, 0.4, 0.3]",ROI
3,P003,Loyalty Bonus,points,100.0,2025-04-26,2025-05-04,Gold+,Nairobi,"['Control', 'Variant A', 'Variant B']","[0.3, 0.4, 0.3]",Conversion Rate
4,P004,Loyalty Bonus,points,100.0,2025-04-26,2025-05-15,Gold+,Nairobi,['All'],[1.0],Usage Frequency

In [176]:
# Display the number of rows and columns
print(f"Rows: {promotions.shape[0]}")
print(f"Columns: {promotions.shape[1]}")

# Display dataset information
promotions.info()

Rows: 20
Columns: 11
<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   promo_id         20 non-null     str
 1   promo_name       20 non-null     str
 2   promo_type       20 non-null     str
 3   promo_value      20 non-null     float64
 4   start_date       20 non-null     datetime64[us]
 5   end_date         20 non-null     datetime64[us]
 6   target_segment   20 non-null     str
 7   city_scope       20 non-null     str
 8   ab_test_groups   20 non-null     str
 9   test_allocation  20 non-null     str
 10  success_metric   20 non-null     str
dtypes: datetime64[us](2), float64(1), str(8)
memory usage: 3.4 KB

In [177]:
# Check for duplicate rows
print("Duplicate rows:", promotions.duplicated().sum())

# Check for duplicate promotion IDs
print("Duplicate Promotion IDs:",
      promotions["promo_id"].duplicated().sum())

# Check missing values
print("\nMissing Values:")
print(promotions.isnull().sum())

# Display the number of unique values in each column
unique_values = pd.DataFrame({
    "Unique Values": promotions.nunique()
})

display(unique_values)

Duplicate rows: 0
Duplicate Promotion IDs: 0

Missing Values:
promo_id           0
promo_name         0
promo_type         0
promo_value        0
start_date         0
end_date           0
target_segment     0
city_scope         0
ab_test_groups     0
test_allocation    0
success_metric     0
dtype: int64

                 Unique Values
promo_id                    20
promo_name                   4
promo_type                   4
promo_value                  4
start_date                   1
end_date                    16
target_segment               4
city_scope                   4
ab_test_groups               2
test_allocation              2
success_metric               3

In [178]:
# Descriptive Statistics

promotions.describe(include="all").T

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
promo_id,20,20,P000,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
promo_name,20,4,First Ride Discount,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
promo_type,20,4,discount,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
promo_value,20.0,NaN,NaN,NaN,26.87,0.3,0.3,1.0,36.25,100.0,43.538115
start_date,20,NaN,NaN,NaN,2025-04-26 00:00:00,2025-04-26 00:00:00,2025-04-26 00:00:00,2025-04-26 00:00:00,2025-04-26 00:00:00,2025-04-26 00:00:00,NaN
end_date,20,NaN,NaN,NaN,2025-05-13 08:24:00,2025-05-03 00:00:00,2025-05-06 00:00:00,2025-05-14 00:00:00,2025-05-18 06:00:00,2025-05-26 00:00:00,NaN
target_segment,20,4,New,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
city_scope,20,4,Nairobi,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ab_test_groups,20,2,['All'],10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
test_allocation,20,2,[1.0],10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
success_metric,20,3,ROI,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [179]:
# Categorical Variable Distribution

exclude_cols = ["promo_id"]

for col in promotions.select_dtypes(include=["object"]).columns:

    if col in exclude_cols:
        continue

    print(f"\nColumn: {col}")
    print("-"*50)

    summary = pd.DataFrame({
        "Count": promotions[col].value_counts(dropna=False),
        "Percentage (%)":
            (
                promotions[col]
                .value_counts(normalize=True)*100
            ).round(2)
    })

    display(summary)

Column: promo_name
--------------------------------------------------

C:\Users\User.DESKTOP-775\AppData\Local\Temp\ipykernel_31880\1492934643.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in promotions.select_dtypes(include=["object"]).columns:

                     Count  Percentage (%)
promo_name
First Ride Discount      8            40.0
Peak Hour Pass           5            25.0
Loyalty Bonus            5            25.0
Referral Special         2            10.0

Column: promo_type
--------------------------------------------------

              Count  Percentage (%)
promo_type
discount          8            40.0
surge_waiver      5            25.0
points            5            25.0
credit            2            10.0

Column: target_segment
--------------------------------------------------

                Count  Percentage (%)
target_segment
New                 8            40.0
All                 5            25.0
Gold+               5            25.0
Active              2            10.0

Column: city_scope
--------------------------------------------------

            Count  Percentage (%)
city_scope
Nairobi         6            30.0
Lagos           5            25.0
All-Cities      5            25.0
Cairo           4            20.0

Column: ab_test_groups
--------------------------------------------------

                                       Count  Percentage (%)
ab_test_groups
['All']                                   10            50.0
['Control', 'Variant A', 'Variant B']     10            50.0

Column: test_allocation
--------------------------------------------------

                 Count  Percentage (%)
test_allocation
[1.0]               10            50.0
[0.3, 0.4, 0.3]     10            50.0

Column: success_metric
--------------------------------------------------

                 Count  Percentage (%)
success_metric
ROI                 10            50.0
Usage Frequency      6            30.0
Conversion Rate      4            20.0

In [180]:

# Promotion Value Summary

print(promotions["promo_value"].describe())

count     20.000000
mean      26.870000
std       43.538115
min        0.300000
25%        0.300000
50%        1.000000
75%       36.250000
max      100.000000
Name: promo_value, dtype: float64

In [181]:

# Campaign Date Range

print("Campaign Start Date Range")
print("-"*35)
print("Earliest:",
      promotions["start_date"].min())
print("Latest:",
      promotions["start_date"].max())

print()

print("Campaign End Date Range")
print("-"*35)
print("Earliest:",
      promotions["end_date"].min())
print("Latest:",
      promotions["end_date"].max())

Campaign Start Date Range
-----------------------------------
Earliest: 2025-04-26 00:00:00
Latest: 2025-04-26 00:00:00

Campaign End Date Range
-----------------------------------
Earliest: 2025-05-03 00:00:00
Latest: 2025-05-26 00:00:00

In [182]:
# Validate Numerical Values

print(
    "Promotion Values Valid:",
    promotions["promo_value"].between(0,100).all()
)

Promotion Values Valid: True